version: '3.9'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgres_data:/var/lib/postgresql/data/ 
    env_file:
      - ./.env.prod

  django:
    restart: always
    build: .
    command: sh -c "python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn --bind 0.0.0.0:8000 yatube.wsgi:application"
    container_name: site
    volumes:   
      - static_value:/app/static
      - media_value:/app/media
    depends_on:
      - db
    env_file:
      - ./.env.prod 

  nginx:
    build: /nginx
    restart: always
    image: nginx:latest
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_value:/app/static
      - media_value:/app/media
      - /app/certbot/conf:/etc/letsencrypt
      - /app/certbot/www:/var/www/certbot
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /app/certbot/conf:/etc/letsencrypt
      - /app/certbot/www:/var/www/certbot

volumes:
  static_value:
  media_value:
  postgres_data:
